//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wplay2.rc
//
#define MainIcon                        1
#define MENU_1                          1
#define MainDialog                      1
#define OptionsDialog                   2
#define AboutDialog                     3
#define OPTION_OK                       8
#define OPTION_CANCEL                   9
#define IDC_GROUPBOX1                   10
#define IDC_GROUPBOX2                   11
#define IDC_GROUPBOX3                   12
#define OPTION_80                       101
#define ID_LISTBOX                      101
#define OPTION_11                       102
#define ID_OPTIONS                      102
#define OPTION_22                       103
#define ID_SAVE                         103
#define OPTION_44                       104
#define ID_DELETE                       104
#define ID_STEREO                       105
#define ID_EXIT                         105
#define OPTION_8                        106
#define ID_ABOUT                        106
#define ID_OK                           106
#define OPTION_16                       107
#define ID_HELP                         107
#define ID_MONO                         108
#define ID_PLAY                         108
#define ID_PAUSE                        109
#define ID_STOP                         110
#define ID_NEXT                         111
#define ID_PREV                         112
#define ID_RECORD                       113
#define ID_DIRECTORY                    114
#define ID_STAT                         115

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
